services:

  mms-api:
    build: 
      context: .
    image: mms-api
    container_name: mms-api
    restart: always
    ports:
      - "9000:9000"
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DELAY_FETCHER_SECONDS=${DELAY_FETCHER_SECONDS}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_ALERT=${EMAIL_ALERT}
    networks:
      - root_mms
  mms-db:
    image: postgres:15
    container_name: mms-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - root_mms

networks:
  root_mms:

volumes:
  pgdata:

